name: Release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish a release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Retrieve new tag
        run: echo "::set-output name=TAG::$(git describe --tags)"
        id: version
    
      - name: Set target python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.6.15"

      - name: Install poetry
        run: python -m pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Update changelog
        run: poetry run scriv collect --version ${{ steps.version.outputs.TAG }}

      - name: Update project version
        run: poetry version ${{ steps.version.outputs.TAG }}
      
      - name: Commit release changes
        run: |
          git config user.name konkolorado
          git config user.email 5422638+konkolorado@users.noreply.github.com
          git add changelog.d/ CHANGELOG.rst pyproject.toml
          git commit -m "Changes for release ${{ steps.version.outputs.TAG }}"
          git push origin HEAD:main

      - name: Build and publish
        env:
          POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
          POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --build

